# Generated by Django 5.0.6 on 2024-06-05 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Cámara')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StreamingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cam', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=1, verbose_name='Número de Cámaras')),
                ('start', models.CharField(default='Iniciar', max_length=20, verbose_name='Iniciar/Detener')),
                ('channel_name', models.CharField(blank=True, max_length=150, verbose_name='Id del canal')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrada')),
                ('cameras', models.ManyToManyField(blank=True, to='streaming.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dsv', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
