# Generated by Django 5.0.6 on 2024-06-06 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name for camera'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='channel_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='channel id'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entry date'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='num_cam',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16')], default=1, verbose_name='Number of cameras'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='start',
            field=models.CharField(default='Start', max_length=20, verbose_name='Start/Stop'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_settings', to=settings.AUTH_USER_MODEL, verbose_name='streaming_settings'),
        ),
    ]
