# Generated by Django 5.0.6 on 2024-06-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_remove_streamingsetting_cameras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingsetting',
            name='num_cam',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Number of cameras'),
        ),
    ]
