# Generated by Django 5.0.6 on 2024-06-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_streamingsetting_cam1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamingsetting',
            name='cam1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Camera 1'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='cam2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Camera 2'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='cam3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Camera 3'),
        ),
        migrations.AlterField(
            model_name='streamingsetting',
            name='cam4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Camera 4'),
        ),
    ]
